version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_inventario
    restart: always
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Titan.1386
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inventario-net

  inventario-backend:
    build: .
    container_name: inventario_backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: inventory_db
      DB_USER: postgres
      DB_PASSWORD: Titan.1386
    networks:
      - inventario-net

networks:
  inventario-net:
    driver: bridge

volumes:
  postgres_data:
